name: Setup node
description: Install node with the desired version and cache its directory

inputs:
  node-version:
    description: 'version'
    required: false
  run_install:
    description: Run pnpm install
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version || env.NODE_VERSION || '20.x' }}
    - name: Get npm cache directory
      id:  npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: |
          ${{ steps.npm-cache-dir.outputs.dir }}
          node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-
    - name: Install dependencies
      if: ${{ inputs.run_install == 'true' }}
      run: npm install
      shell: bash
